name: Check Website Status

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:       # Allows manual triggering

jobs:
  check_website:
    runs-on: ubuntu-latest

    steps:
    - name: Check website status
      run: |
        CODE=`curl --write-out '%{http_code}' \
            --silent \
            --output /dev/null \
            --url ${{vars.WEBSITE_URL}} \
            
        if [ $CODE!="200" ] 
        then
            echo "FAILURE"
        else
            echo "SUCCESS"
        fi
